<?php
	$selectedTime = $this->getSelection();
?>

<?php if ($selectedTime): ?>
<style type="text/css">
	.nektria_user_selection ul li{
		list-style: none;
	}
	.nektria_user_selection{
		margin-top: 10px;
		font-size: 0.95em;
	}
</style>
<div class="nektria_user_selection">
	<?php echo $this->__('Selected delivery'); ?><br />
	<ul>
	<?php if(isset($selectedTime['delivery_windows'])): ?>
		<?php foreach ($selectedTime['delivery_windows'] as $selectedDate): ?>
			<li><?php 
				echo $this->__('from').
					': '.Mage::getModel('core/date')->date('H:i', strtotime($selectedDate['start_time'])).
					' '.Mage::helper('nektria')->_('to').
					': '.Mage::getModel('core/date')->date('H:i', strtotime($selectedDate['end_time'])).
					' '.Mage::helper('nektria')->_('for').
					': '.Mage::getModel('core/date')->date('d/m/y', strtotime($selectedDate['end_time'])); 
					?></li>
		<?php endforeach ?>
	<?php endif; ?>
	</ul>
</div>
<?php endif; ?>